name: Release Terraform Modules

on:
  push:
    branches: [main]
    paths:
      - 'modules/**'

permissions:
  contents: write

jobs:
  release:
    uses: jjchange10/test-actions/.github/workflows/secure-job.yml@main
    with:
      egress-policy: audit
    secrets: inherit
